org: brajanieto
service: api-inmo

provider:
  name: aws
  runtime: python3.13
  memorySize: 1024
  timeout: 20
  environment:
    CLIENTES_TABLE: clientes
    PROYECTOS_TABLE: proyectos
    AGENTES_TABLE: agentes
    CONSULTAS_TABLE: consultas
  iam:
    role: arn:aws:iam::654654276465:role/LabRole

package:
  patterns:
    - "!**/__pycache__/**"
    - "!frontend/**"

functions:
  # ---------- CLIENTES ----------
  crearCliente:
    handler: clientes/crear.lambda_handler
    events:
      - http:
          path: clientes/crear
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
            methods:
              - OPTIONS
              - POST

  listarClientes:
    handler: clientes/listar.lambda_handler
    events:
      - http:
          path: clientes/listar
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
            methods:
              - OPTIONS
              - GET

  buscarCliente:
    handler: clientes/buscar.lambda_handler
    events:
      - http:
          path: clientes/buscar
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
            methods:
              - OPTIONS
              - POST

  actualizarCliente:
    handler: clientes/actualizar.lambda_handler
    events:
      - http:
          path: clientes/actualizar
          method: put
          cors:
            origin: '*'
            headers:
              - Content-Type
            methods:
              - OPTIONS
              - PUT

  eliminarCliente:
    handler: clientes/eliminar.lambda_handler
    events:
      - http:
          path: clientes/eliminar
          method: delete
          cors:
            origin: '*'
            headers:
              - Content-Type
            methods:
              - OPTIONS
              - DELETE

  # ---------- PROYECTOS ----------
  crearProyecto:
    handler: proyectos/crear.lambda_handler
    events:
      - http:
          path: proyectos/crear
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
            methods:
              - OPTIONS
              - POST

  listarProyectos:
    handler: proyectos/listar.lambda_handler
    events:
      - http:
          path: proyectos/listar
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
            methods:
              - OPTIONS
              - GET

  buscarProyecto:
    handler: proyectos/buscar.lambda_handler
    events:
      - http:
          path: proyectos/buscar
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
            methods:
              - OPTIONS
              - POST

  actualizarProyecto:
    handler: proyectos/actualizar.lambda_handler
    events:
      - http:
          path: proyectos/actualizar
          method: put
          cors:
            origin: '*'
            headers:
              - Content-Type
            methods:
              - OPTIONS
              - PUT

  eliminarProyecto:
    handler: proyectos/eliminar.lambda_handler
    events:
      - http:
          path: proyectos/eliminar
          method: delete
          cors:
            origin: '*'
            headers:
              - Content-Type
            methods:
              - OPTIONS
              - DELETE

  # ---------- AGENTES ----------
  crearAgente:
    handler: agentes/crear.lambda_handler
    events:
      - http:
          path: agentes/crear
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
            methods:
              - OPTIONS
              - POST

  listarAgentes:
    handler: agentes/listar.lambda_handler
    events:
      - http:
          path: agentes/listar
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
            methods:
              - OPTIONS
              - GET

  buscarAgente:
    handler: agentes/buscar.lambda_handler
    events:
      - http:
          path: agentes/buscar
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
            methods:
              - OPTIONS
              - POST

  actualizarAgente:
    handler: agentes/actualizar.lambda_handler
    events:
      - http:
          path: agentes/actualizar
          method: put
          cors:
            origin: '*'
            headers:
              - Content-Type
            methods:
              - OPTIONS
              - PUT

  eliminarAgente:
    handler: agentes/eliminar.lambda_handler
    events:
      - http:
          path: agentes/eliminar
          method: delete
          cors:
            origin: '*'
            headers:
              - Content-Type
            methods:
              - OPTIONS
              - DELETE

  # ---------- CONSULTAS / INTERACCIONES ----------
  registrarConsulta:
    handler: consultas/registrar.lambda_handler
    events:
      - http:
          path: consultas/registrar
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
            methods:
              - OPTIONS
              - POST

  listarConsultasPorCliente:
    handler: consultas/listar_por_cliente.lambda_handler
    events:
      - http:
          path: consultas/cliente
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
            methods:
              - OPTIONS
              - POST
